import AppKit
import ServiceManagement

let maxClipboardBytes = 64 * 1024 // 与服务端上限一致

// MARK: - 数据

struct ClipItem: Decodable {
    let text: String
    let sender: String?
    let sender_id: String?
    let updated_at: Double?
}

struct Device: Decodable {
    let id: String
    let name: String
    let type: String
}

// MARK: - 设置

final class Settings {
    private let d = UserDefaults.standard

    var server: String {
        get { d.string(forKey: "server") ?? defaultServer }
        set { d.set(newValue, forKey: "server") }
    }
    var token: String {
        get { d.string(forKey: "token") ?? defaultToken }
        set { d.set(newValue, forKey: "token") }
    }
    var deviceName: String {
        get { d.string(forKey: "deviceName") ?? (Host.current().localizedName ?? "Mac") }
        set { d.set(newValue, forKey: "deviceName") }
    }
    var paused: Bool {
        get { d.bool(forKey: "paused") }
        set { d.set(newValue, forKey: "paused") }
    }
    lazy var deviceId: String = {
        if let id = d.string(forKey: "deviceId") { return id }
        let id = "mac_" + UUID().uuidString.prefix(8).lowercased()
        d.set(id, forKey: "deviceId")
        return id
    }()
}

// MARK: - 剪贴板监听

final class ClipboardWatcher {
    private let pb = NSPasteboard.general
    private var lastChange: Int
    private var timer: Timer?
    var onCopy: (String) -> Void = { _ in }

    // 密码管理器等会给敏感内容打这些标记，不同步
    private static let skipTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
    ]

    init() {
        lastChange = pb.changeCount // 启动时不推送已有内容
    }

    func start() {
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in self?.poll() }
    }

    private func poll() {
        guard pb.changeCount != lastChange else { return }
        lastChange = pb.changeCount
        let types = Set((pb.types ?? []).map(\.rawValue))
        guard types.isDisjoint(with: Self.skipTypes) else { return }
        guard let text = pb.string(forType: .string),
              !text.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return }
        onCopy(text)
    }

    /// 写入剪贴板，并记下 changeCount，避免被当成本机复制再推回去
    func write(_ text: String) {
        pb.clearContents()
        pb.setString(text, forType: .string)
        lastChange = pb.changeCount
    }
}

// MARK: - 中枢连接

final class Hub: NSObject, URLSessionWebSocketDelegate {
    enum Status { case notConfigured, connecting, online, offline, unauthorized }

    let settings: Settings
    private(set) var status: Status = .connecting { didSet { onChange() } }
    private(set) var history: [ClipItem] = []
    private(set) var devices: [Device] = []
    var onChange: () -> Void = {}
    var onReceived: (ClipItem) -> Void = { _ in }

    private var session: URLSession!
    private var task: URLSessionWebSocketTask?
    private var pingTimer: Timer?
    private var reconnectTimer: Timer?
    private var pending: String?

    init(settings: Settings) {
        self.settings = settings
        super.init()
        session = URLSession(configuration: .default, delegate: self, delegateQueue: .main)
    }

    func connect() {
        reconnectTimer?.invalidate()
        pingTimer?.invalidate()
        task?.cancel(with: .goingAway, reason: nil)
        task = nil

        guard !settings.server.isEmpty, !settings.token.isEmpty,
              var comps = URLComponents(string: settings.server) else {
            status = .notConfigured
            return
        }
        comps.scheme = comps.scheme == "https" ? "wss" : "ws"
        comps.path = "/ws"
        comps.queryItems = [
            URLQueryItem(name: "device_id", value: settings.deviceId),
            URLQueryItem(name: "name", value: settings.deviceName),
            URLQueryItem(name: "device_type", value: "mac"),
            URLQueryItem(name: "token", value: settings.token),
        ]
        guard let url = comps.url else {
            status = .notConfigured
            return
        }
        status = .connecting
        let t = session.webSocketTask(with: url)
        task = t
        t.resume()
        receive(t)
    }

    private func receive(_ t: URLSessionWebSocketTask) {
        t.receive { [weak self] result in
            DispatchQueue.main.async {
                guard let self, t === self.task else { return }
                switch result {
                case .success(.string(let s)):
                    self.handle(s)
                    self.receive(t)
                case .success:
                    self.receive(t)
                case .failure:
                    self.closed(t, code: t.closeCode.rawValue)
                }
            }
        }
    }

    private func closed(_ t: URLSessionWebSocketTask, code: Int) {
        if code == 4001 {
            reconnectTimer?.invalidate()
            task = nil
            status = .unauthorized
            return
        }
        guard t === task else { return }
        task = nil
        pingTimer?.invalidate()
        status = .offline
        reconnectTimer = Timer.scheduledTimer(withTimeInterval: 3, repeats: false) { [weak self] _ in self?.connect() }
    }

    func urlSession(_ session: URLSession, webSocketTask: URLSessionWebSocketTask, didOpenWithProtocol protocol: String?) {
        guard webSocketTask === task else { return }
        status = .online
        pingTimer = Timer.scheduledTimer(withTimeInterval: 20, repeats: true) { [weak webSocketTask] _ in
            webSocketTask?.sendPing { _ in }
        }
        if let p = pending {
            pending = nil
            send(p)
        }
    }

    func urlSession(_ session: URLSession, webSocketTask: URLSessionWebSocketTask,
                    didCloseWith closeCode: URLSessionWebSocketTask.CloseCode, reason: Data?) {
        closed(webSocketTask, code: closeCode.rawValue)
    }

    private func handle(_ raw: String) {
        guard let data = raw.data(using: .utf8),
              let obj = try? JSONSerialization.jsonObject(with: data) as? [String: Any],
              let type = obj["type"] as? String else { return }
        let dec = JSONDecoder()
        func decode<T: Decodable>(_ key: String, as: T.Type) -> T? {
            guard let v = obj[key], let d = try? JSONSerialization.data(withJSONObject: v) else { return nil }
            return try? dec.decode(T.self, from: d)
        }
        switch type {
        case "clipboard:history":
            history = decode("history", as: [ClipItem].self) ?? []
            onChange()
        case "clipboard:sync":
            guard let item = decode("data", as: ClipItem.self) else { return }
            add(item)
            if item.sender_id != settings.deviceId { onReceived(item) }
        case "devices:update":
            devices = decode("devices", as: [Device].self) ?? []
            onChange()
        case "clipboard:error":
            NSLog("NelsonBox: %@", obj["error"] as? String ?? "error")
        default:
            break
        }
    }

    func send(_ text: String) {
        guard text.utf8.count <= maxClipboardBytes else {
            NSLog("NelsonBox: 内容超过 64KB，跳过")
            return
        }
        add(ClipItem(text: text, sender: settings.deviceName, sender_id: settings.deviceId,
                     updated_at: Date().timeIntervalSince1970))
        guard status == .online, let task else {
            pending = text // 断线期间只保留最后一条
            return
        }
        let payload = try! JSONSerialization.data(withJSONObject: ["type": "clipboard:send", "text": text])
        task.send(.string(String(decoding: payload, as: UTF8.self))) { _ in }
    }

    private func add(_ item: ClipItem) {
        history.removeAll { $0.text == item.text }
        history.insert(item, at: 0)
        if history.count > 50 { history.removeLast(history.count - 50) }
        onChange()
    }
}

// MARK: - 菜单栏

final class AppDelegate: NSObject, NSApplicationDelegate, NSMenuDelegate {
    let settings = Settings()
    lazy var hub = Hub(settings: settings)
    let watcher = ClipboardWatcher()
    var statusItem: NSStatusItem!

    func applicationDidFinishLaunching(_ notification: Notification) {
        statusItem = NSStatusBar.system.statusItem(withLength: NSStatusItem.squareLength)
        statusItem.button?.image = NSImage(systemSymbolName: "doc.on.clipboard", accessibilityDescription: "NelsonBox")
        let menu = NSMenu()
        menu.delegate = self
        statusItem.menu = menu

        watcher.onCopy = { [weak self] text in
            guard let self, !self.settings.paused else { return }
            self.hub.send(text)
        }
        hub.onReceived = { [weak self] item in
            guard let self, !self.settings.paused else { return }
            self.watcher.write(item.text)
            self.flashIcon()
        }
        hub.onChange = { [weak self] in self?.updateIcon() }

        watcher.start()
        hub.connect()
        updateIcon()

        if settings.token.isEmpty { showSettings() }
    }

    private func updateIcon() {
        statusItem.button?.appearsDisabled = hub.status != .online || settings.paused
    }

    /// 收到内容时图标短暂变成实心
    private func flashIcon() {
        statusItem.button?.image = NSImage(systemSymbolName: "doc.on.clipboard.fill", accessibilityDescription: "NelsonBox")
        DispatchQueue.main.asyncAfter(deadline: .now() + 1.2) { [weak self] in
            self?.statusItem.button?.image = NSImage(systemSymbolName: "doc.on.clipboard", accessibilityDescription: "NelsonBox")
        }
    }

    func menuNeedsUpdate(_ menu: NSMenu) {
        menu.removeAllItems()

        let statusText: String = switch hub.status {
        case .online: "已连接 · \(hub.devices.count) 台在线"
        case .connecting: "连接中…"
        case .offline: "已断开，正在重连…"
        case .unauthorized: "令牌错误，请检查设置"
        case .notConfigured: "未设置服务器"
        }
        menu.addItem(withTitle: statusText, action: nil, keyEquivalent: "")
        if hub.status == .online {
            for d in hub.devices where d.id != settings.deviceId {
                let item = menu.addItem(withTitle: "    \(d.name)", action: nil, keyEquivalent: "")
                item.indentationLevel = 1
            }
        }
        menu.addItem(.separator())

        menu.addItem(withTitle: "最近记录（点击复制）", action: nil, keyEquivalent: "")
        if hub.history.isEmpty {
            menu.addItem(withTitle: "    暂无", action: nil, keyEquivalent: "")
        }
        for (i, h) in hub.history.prefix(10).enumerated() {
            let item = NSMenuItem(title: preview(h.text), action: #selector(copyHistory(_:)), keyEquivalent: "")
            item.target = self
            item.tag = i
            item.toolTip = "来自 \(h.sender ?? "未知")"
            menu.addItem(item)
        }
        menu.addItem(.separator())

        let pause = NSMenuItem(title: "暂停同步", action: #selector(togglePause), keyEquivalent: "")
        pause.target = self
        pause.state = settings.paused ? .on : .off
        menu.addItem(pause)

        let login = NSMenuItem(title: "登录时自动启动", action: #selector(toggleLogin), keyEquivalent: "")
        login.target = self
        login.state = SMAppService.mainApp.status == .enabled ? .on : .off
        menu.addItem(login)

        let reconnect = NSMenuItem(title: "重新连接", action: #selector(reconnectNow), keyEquivalent: "r")
        reconnect.target = self
        menu.addItem(reconnect)

        let settingsItem = NSMenuItem(title: "设置…", action: #selector(showSettings), keyEquivalent: ",")
        settingsItem.target = self
        menu.addItem(settingsItem)

        menu.addItem(.separator())
        menu.addItem(withTitle: "退出 NelsonBox", action: #selector(NSApplication.terminate(_:)), keyEquivalent: "q")
    }

    private func preview(_ text: String) -> String {
        let s = text.replacingOccurrences(of: "\n", with: " ").trimmingCharacters(in: .whitespaces)
        return s.count > 40 ? String(s.prefix(40)) + "…" : s
    }

    @objc private func copyHistory(_ sender: NSMenuItem) {
        guard sender.tag < hub.history.count else { return }
        watcher.write(hub.history[sender.tag].text)
    }

    @objc private func togglePause() {
        settings.paused.toggle()
        updateIcon()
    }

    @objc private func reconnectNow() {
        hub.connect()
    }

    @objc private func toggleLogin() {
        do {
            if SMAppService.mainApp.status == .enabled {
                try SMAppService.mainApp.unregister()
            } else {
                try SMAppService.mainApp.register()
            }
        } catch {
            let alert = NSAlert()
            alert.messageText = "设置自动启动失败"
            alert.informativeText = "\(error.localizedDescription)\n\n可以在“系统设置 › 通用 › 登录项”里手动添加 NelsonBox。"
            NSApp.activate(ignoringOtherApps: true)
            alert.runModal()
        }
    }

    @objc private func showSettings() {
        let server = NSTextField(string: settings.server)
        let token = NSSecureTextField(string: settings.token)
        let name = NSTextField(string: settings.deviceName)
        server.placeholderString = "http://1.2.3.4:18888"
        token.placeholderString = "访问令牌"
        for f in [server, token, name] { f.widthAnchor.constraint(equalToConstant: 300).isActive = true }

        func row(_ label: String, _ field: NSView) -> NSView {
            let l = NSTextField(labelWithString: label)
            l.widthAnchor.constraint(equalToConstant: 70).isActive = true
            return NSStackView(views: [l, field])
        }
        let stack = NSStackView(views: [row("服务器", server), row("令牌", token), row("设备名", name)])
        stack.orientation = .vertical
        stack.alignment = .leading
        stack.frame = NSRect(x: 0, y: 0, width: 380, height: 90)

        let alert = NSAlert()
        alert.messageText = "NelsonBox 设置"
        alert.accessoryView = stack
        alert.addButton(withTitle: "保存")
        alert.addButton(withTitle: "取消")
        NSApp.activate(ignoringOtherApps: true)
        guard alert.runModal() == .alertFirstButtonReturn else { return }

        settings.server = server.stringValue.trimmingCharacters(in: .whitespaces)
            .replacingOccurrences(of: "/+$", with: "", options: .regularExpression)
        settings.token = token.stringValue.trimmingCharacters(in: .whitespaces)
        let n = name.stringValue.trimmingCharacters(in: .whitespaces)
        if !n.isEmpty { settings.deviceName = n }
        hub.connect()
    }
}

let app = NSApplication.shared
let delegate = AppDelegate()
app.delegate = delegate
app.setActivationPolicy(.accessory)
app.run()
